language: java
before_install:
  - npm install
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
sudo: false
script:
  - mvn package
  - mvn checkstyle:check
  - npm test
  - npm run lint-js
  - npm run lint-md
